#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include "PrepareData.h"
#include <fstream>

#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/colourdata.h>
#include <wx/colordlg.h>

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void m_button1_click( wxCommandEvent& event );
		void m_button2_click( wxCommandEvent& event );
		void m_button3_click( wxCommandEvent& event );
		void m_button4_click( wxCommandEvent& event );
		void m_cb_color_click( wxCommandEvent& event );
		void m_s_rotation_onscroll( wxScrollEvent& event );
		void m_s_tilt_onscroll( wxScrollEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
		~GUIMyFrame1();

		std::fstream plik;

	//// end generated class members
		void Repaint();









};

#endif // __GUIMyFrame1__
